"""Public AgentRunner façade that orchestrates the specialized runner subsystems."""

import asyncio
import time
from typing import Any, Callable, Dict, List, Optional

import structlog

from ..client import CoreClient
from ..logging import configure_logging
from ..models import AgentConfig
from ..pii_keeper_client import PIIKeeperClient
from ..tools import (
    DATETIME_DEF,
    STAGE_REPLY_ATTACHMENT_DEF,
    discover_skills,
    DISCOVER_SKILLS_DEF,
    get_current_datetime,
    stage_reply_attachment,
)
from .constants import CIRCUIT_HALF_OPEN_AFTER
from .lifecycle import LifecycleManager
from .model_client import ModelClient
from .parsing import (
    _ParsedToolCall,
    extract_json_tool_calls,
    extract_legacy_tool_calls,
    extract_tool_calls,
    extract_xml_tool_calls,
    strip_json_tool_calls,
    strip_legacy_tool_calls,
    strip_tool_calls,
    strip_xml_tool_calls,
)
from .pii_manager import PIIManager
from .prompt_assembler import PromptAssembler
from .react_loop import ReActLoop
from .streaming import Streamer
from .tool_engine import ToolEngine

logger = structlog.get_logger()


class AgentRunner:
    """
    The Opinionated ISLI Agent Runner.
    Automates heartbeats, WebSocket connectivity, context injection,
    and the ReAct execution loop with dual-checkpointing.

    This class is a thin façade over focused subsystems in the ``runner``
    package. Method and attribute names are preserved for backward
    compatibility.
    """

    def __new__(cls, *args, **kwargs):
        """Create instance and pre-initialize helper subsystems.

        Tests occasionally bypass ``__init__`` with ``AgentRunner.__new__``.
        Pre-wiring the helpers here ensures every instance can use the
        backward-compatible delegate methods regardless of how it was
        constructed.
        """
        instance = super().__new__(cls)
        # Minimal defaults required by helper constructors and delegate methods.
        instance.tools = {}
        instance.tool_definitions = []
        instance._running = False
        instance._pending_components = []
        instance._inflight_sessions = set()
        instance._websocket = None
        instance._outgoing_queue = asyncio.Queue(maxsize=1000)
        instance._current_session_metadata = {}
        instance._pending_audio = {}
        instance._pending_attachments = {}
        instance._session_token_maps = {}
        instance._model_circuit_open = False
        instance._circuit_open_reason = None
        instance._circuit_tripped_at = None
        instance._consecutive_auth_failures = 0
        instance._pending_tool_reload = False
        instance._all_tool_definitions = []
        instance._active_tool_definitions = []
        instance._expand_tools_next_iteration = False

        # Subsystems (re-created by __init__ for normal construction, but
        # present immediately for tests that skip __init__).
        instance._model_client = ModelClient(instance)
        instance._tool_engine = ToolEngine(instance)
        instance._prompt_assembler = PromptAssembler(instance)
        instance._streamer = Streamer(instance)
        instance._pii_manager = PIIManager(instance)
        instance._lifecycle = LifecycleManager(instance)
        instance._react_loop = ReActLoop(instance)
        return instance

    def __init__(self, config: AgentConfig, core_url: str, admin_key: Optional[str] = None):
        # Guard: default model must be configured. These are the ground-truth
        # fallback for model routing. Fail loudly at startup if missing.
        if not config.model_provider or not config.model_id:
            raise ValueError(
                f"Agent {config.id} must have model_provider and model_id configured. "
                "These are the ground-truth fallback for model routing."
            )
        self.config = config
        self.core_url = core_url
        self.client = CoreClient(core_url, admin_key=admin_key)
        self.tools: Dict[str, Callable] = {}
        self.tool_definitions: List[Dict[str, Any]] = []
        self._running = False
        self._pending_components: List[Dict[str, Any]] = []
        self._inflight_sessions: set = set()
        self._websocket: Optional[Any] = None
        self._outgoing_queue: asyncio.Queue = asyncio.Queue(maxsize=1000)
        self._current_session_metadata: dict = {}
        # Pending audio generated by text_to_speech to attach to the next session reply
        self._pending_audio: dict[str, dict[str, Any]] = {}
        # Pending file attachments staged by the agent for the next session reply
        self._pending_attachments: dict[str, list[dict[str, Any]]] = {}
        # PII Mesh client and per-session token maps
        self._pii_client = PIIKeeperClient()
        self._session_token_maps: dict[str, dict[str, str]] = {}
        # Circuit breaker for sustained model auth failures
        self._model_circuit_open: bool = False
        self._circuit_open_reason: str | None = None
        self._circuit_tripped_at: float | None = None
        self._consecutive_auth_failures: int = 0
        # Drain-and-swap flag for skill:updated events
        self._pending_tool_reload: bool = False

        # Subsystems
        self._model_client = ModelClient(self)
        self._tool_engine = ToolEngine(self)
        self._prompt_assembler = PromptAssembler(self)
        self._streamer = Streamer(self)
        self._pii_manager = PIIManager(self)
        self._lifecycle = LifecycleManager(self)
        self._react_loop = ReActLoop(self)

    # ── Tool registration convenience methods ──────────────────────────────────

    def add_tool(self, name: str, func: Callable, definition: Dict[str, Any], skill_name: str | None = None):
        """Register a tool with the agent."""
        self._tool_engine.add_tool(name, func, definition, skill_name=skill_name)

    def add_dynamic_tool(self, name: str, func: Callable, definition: Dict[str, Any], skill_name: str | None = None):
        """Register a dynamic skill tool without Pydantic validation."""
        self._tool_engine.add_dynamic_tool(name, func, definition, skill_name=skill_name)

    def add_workspace_tools(self):
        """Convenience method to register all workspace file tools."""
        from ..tools import (
            file_read,
            FILE_READ_DEF,
            file_write,
            FILE_WRITE_DEF,
            file_list,
            FILE_LIST_DEF,
            file_delete,
            FILE_DELETE_DEF,
            describe_workspace_file,
            DESCRIBE_WORKSPACE_FILE_DEF,
            search_workspace_file,
            SEARCH_WORKSPACE_FILE_DEF,
            read_workspace_file,
            READ_WORKSPACE_FILE_DEF,
        )

        self.add_tool("file_read", file_read, FILE_READ_DEF)
        self.add_tool("file_write", file_write, FILE_WRITE_DEF)
        self.add_tool("file_list", file_list, FILE_LIST_DEF)
        self.add_tool("file_delete", file_delete, FILE_DELETE_DEF)
        self.add_tool("describe_workspace_file", describe_workspace_file, DESCRIBE_WORKSPACE_FILE_DEF)
        self.add_tool("search_workspace_file", search_workspace_file, SEARCH_WORKSPACE_FILE_DEF)
        self.add_tool("read_workspace_file", read_workspace_file, READ_WORKSPACE_FILE_DEF)

    def add_shared_workspace_tools(self):
        """Convenience method to register all shared workspace tools."""
        from ..tools import (
            shared_promote_file_workspace,
            SHARED_PROMOTE_FILE_WORKSPACE_DEF,
            shared_file_read,
            SHARED_FILE_READ_DEF,
            shared_file_write,
            SHARED_FILE_WRITE_DEF,
            shared_file_list,
            SHARED_FILE_LIST_DEF,
            shared_file_delete,
            SHARED_FILE_DELETE_DEF,
            shared_file_move,
            SHARED_FILE_MOVE_DEF,
            shared_workspace_info,
            SHARED_WORKSPACE_INFO_DEF,
            shared_workspace_search,
            SHARED_WORKSPACE_SEARCH_DEF,
        )

        self.add_tool("shared_promote_file_workspace", shared_promote_file_workspace, SHARED_PROMOTE_FILE_WORKSPACE_DEF)
        self.add_tool("shared_file_read", shared_file_read, SHARED_FILE_READ_DEF)
        self.add_tool("shared_file_write", shared_file_write, SHARED_FILE_WRITE_DEF)
        self.add_tool("shared_file_list", shared_file_list, SHARED_FILE_LIST_DEF)
        self.add_tool("shared_file_delete", shared_file_delete, SHARED_FILE_DELETE_DEF)
        self.add_tool("shared_file_move", shared_file_move, SHARED_FILE_MOVE_DEF)
        self.add_tool("shared_workspace_info", shared_workspace_info, SHARED_WORKSPACE_INFO_DEF)
        self.add_tool("shared_workspace_search", shared_workspace_search, SHARED_WORKSPACE_SEARCH_DEF)

    @property
    def _pii_mesh_enabled(self) -> bool:
        return self._pii_manager.mesh_enabled

    @property
    def _pii_use_slm(self) -> bool:
        return self._pii_manager.use_slm

    def add_channel_tools(self):
        """Convenience method to register channel communication tools."""
        from ..tools import send_message, SEND_MESSAGE_DEF
        self.add_tool("send_message", send_message, SEND_MESSAGE_DEF)

    def add_notification_tools(self):
        """Convenience method to register the notify_user tool."""
        from ..tools import notify_user, NOTIFY_USER_DEF
        self.add_tool("notify_user", notify_user, NOTIFY_USER_DEF)

    async def _auto_register_tools_from_skills(self):
        """Register tools based on the synced config.skills list from Core."""
        await self._tool_engine.auto_register_from_skills()

    # ── Backward-compatible tool / parsing delegates ─────────────────────────────

    async def _execute_tool(self, tool_name: str, tool_args: dict, session_id: str | None = None) -> str:
        return await self._tool_engine.execute(tool_name, tool_args, session_id=session_id)

    def _filter_tools_by_relevance(self, relevant_skills: list[str] | None) -> list[dict[str, Any]]:
        return self._tool_engine.filter_by_relevance(relevant_skills)

    def _extract_xml_tool_calls(self, content: str) -> list[_ParsedToolCall]:
        return extract_xml_tool_calls(content)

    def _extract_json_tool_calls(self, content: str) -> list[_ParsedToolCall]:
        return extract_json_tool_calls(content, self.tools)

    def _extract_legacy_tool_calls(self, content: str) -> list[_ParsedToolCall]:
        return extract_legacy_tool_calls(content, self.tools)

    def _extract_tool_calls(self, message) -> list[Any]:
        return extract_tool_calls(message, self.tools)

    @staticmethod
    def _strip_xml_tool_calls(content: str) -> str:
        return strip_xml_tool_calls(content)

    def _strip_json_tool_calls(self, content: str) -> str:
        return strip_json_tool_calls(content, self.tools)

    @staticmethod
    def _strip_legacy_tool_calls(content: str) -> str:
        return strip_legacy_tool_calls(content)

    def _strip_tool_calls(self, content: str) -> str:
        return strip_tool_calls(content, self.tools)

    # ── Backward-compatible streaming delegates ──────────────────────────────────

    def _resolve_streaming_mode(self, session_id: str) -> str:
        return self._streamer._resolve_streaming_mode(session_id)

    async def _emit_stream_event(self, session_id: str, event_type: str, data: dict):
        await self._streamer.emit_event(session_id, event_type, data)

    async def _stream_text(self, session_id: str, text: str):
        await self._streamer.stream_text(session_id, text)

    async def _drain_outgoing_queue(self):
        await self._streamer.drain_outgoing_queue()

    # ── Backward-compatible model client delegates ───────────────────────────────

    def _resolve_model(self, routed: dict | None = None) -> str:
        return self._model_client.resolve_model(routed)

    def _ollama_openai_provider(self, provider: str) -> str:
        return self._model_client._ollama_openai_provider(provider)

    async def _acompletion_with_retry(self, completion_kwargs: dict[str, Any], turn_label: str) -> Any:
        return await self._model_client.acompletion_with_retry(completion_kwargs, turn_label)

    def _apply_auth_to_kwargs(self, completion_kwargs: dict[str, Any]) -> None:
        self._model_client.apply_auth_to_kwargs(completion_kwargs)

    async def _model_with_fallback(self, completion_kwargs: dict, turn_label: str) -> Any:
        return await self._model_client.model_with_fallback(completion_kwargs, turn_label)

    def _truncate_tool_results_to_cap(self, messages: list[dict], max_tokens: int = 1000) -> list[dict]:
        return self._model_client.truncate_tool_results_to_cap(messages, max_tokens)

    # ── Backward-compatible prompt / PII delegates ─────────────────────────────

    def _assemble_system_prompt(
        self,
        context_summary: str,
        session_info: dict | None = None,
        relevant_skills: list[str] | None = None,
        task_mode: bool = False,
    ) -> str:
        return self._prompt_assembler.assemble(context_summary, session_info, relevant_skills, task_mode)

    @staticmethod
    def _build_tool_fallback_summary(messages: list[dict]) -> str:
        return PromptAssembler.build_tool_fallback_summary(messages)

    async def _prepare_llm_payload(
        self, system_prompt: str, messages: list[dict], session_id: str
    ) -> tuple[str, list[dict]]:
        return await self._pii_manager.prepare_llm_payload(system_prompt, messages, session_id)

    def _post_process_response(self, text: str, session_id: str) -> str:
        return self._pii_manager.post_process_response(text, session_id)

    # ── Backward-compatible lifecycle delegates ──────────────────────────────────

    async def _sync_config(self):
        await self._lifecycle.sync_config()

    async def _heartbeat_loop(self):
        await self._lifecycle.heartbeat_loop()

    async def _ws_loop(self):
        await self._lifecycle.ws_loop()

    async def _notify_core_session_ready(self, session_id: str):
        await self._lifecycle.notify_session_ready(session_id)

    # ── ReAct loop delegates ─────────────────────────────────────────────────────

    async def _execute_task(self, task_data: dict):
        await self._react_loop.execute_task(task_data)

    async def _execute_session_message(self, payload: dict):
        await self._react_loop.execute_session_message(payload)

    # ── Startup / shutdown ─────────────────────────────────────────────────────

    async def start(self):
        """Start the agent: registration, heartbeat, and WebSocket listener."""
        self._running = True
        configure_logging(self.config.id)
        logger.info("runner.starting", agent_id=self.config.id)

        # 1. Register with Core and sync config
        reg_data = await self.client.register(self.config)
        if reg_data:
            self.config = AgentConfig.model_validate(reg_data)
            logger.info(
                "runner.config_synced",
                agent_id=self.config.id,
                skills=self.config.skills,
            )

        # 2. Restore circuit breaker from Core status (restart consistency)
        # Config may not always include status/status_reason, so use getattr guards
        agent_status = getattr(self.config, "status", None)
        agent_status_reason = getattr(self.config, "status_reason", None)
        if agent_status == "flagged" and agent_status_reason and "auth_error" in agent_status_reason:
            self._model_circuit_open = True
            self._circuit_open_reason = agent_status_reason
            # Allow immediate half-open probe on restart — operator may have fixed the key
            self._circuit_tripped_at = time.monotonic() - CIRCUIT_HALF_OPEN_AFTER - 1
            logger.warning(
                "runner.model_circuit_restored_from_core",
                agent_id=self.config.id,
                reason=self._circuit_open_reason,
            )

        # 3. Auto-register tools from synced skills
        await self._auto_register_tools_from_skills()

        # 4. Always register universal tools
        self.add_tool("get_current_datetime", get_current_datetime, DATETIME_DEF)
        self.add_tool("stage_reply_attachment", stage_reply_attachment, STAGE_REPLY_ATTACHMENT_DEF)

        # 5. Snapshot full tool set for per-turn filtering
        self._all_tool_definitions: list[dict[str, Any]] = list(self.tool_definitions)
        self._active_tool_definitions: list[dict[str, Any]] = list(self.tool_definitions)
        self._expand_tools_next_iteration: bool = False

        # discover_skills wrapper reads the current list at call time (not capture time)
        def _discover_skills_wrapper():
            return discover_skills(self._all_tool_definitions)

        self.add_tool("discover_skills", _discover_skills_wrapper, DISCOVER_SKILLS_DEF)

        # 6. Start heartbeat loop in background
        asyncio.create_task(self._heartbeat_loop())

        # 5. Start WebSocket listener (main loop)
        await self._ws_loop()

    async def stop(self):
        """Gracefully stop the agent."""
        self._running = False
        await self.client.close()
