from .workspace import (
    file_read,
    file_write,
    file_list,
    file_delete,
    FILE_READ_DEF,
    FILE_WRITE_DEF,
    FILE_LIST_DEF,
    FILE_DELETE_DEF,
    attach_to_task,
    ATTACH_TO_TASK_DEF,
    pull_task_attachment,
    PULL_TASK_ATTACHMENT_DEF,
    promote_output,
    PROMOTE_OUTPUT_DEF,
    shared_file_read,
    SHARED_FILE_READ_DEF,
    shared_file_write,
    SHARED_FILE_WRITE_DEF,
    shared_file_list,
    SHARED_FILE_LIST_DEF,
    WorkspacePathError,
    WorkspaceQuotaError,
    WorkspaceNotFoundError,
    WorkspacePermissionError,
)
from .channels import send_message, SEND_MESSAGE_DEF
from .system import get_current_datetime, shell_exec, DATETIME_DEF, SHELL_EXEC_DEF
from .web import (
    web_fetch,
    WEB_FETCH_DEF,
    web_search,
    WEB_SEARCH_DEF,
    browser_navigate,
    BROWSER_NAVIGATE_DEF,
    browser_snapshot,
    BROWSER_SNAPSHOT_DEF,
    browser_click,
    BROWSER_CLICK_DEF,
    browser_type,
    BROWSER_TYPE_DEF,
    browser_press,
    BROWSER_PRESS_DEF,
    browser_scroll,
    BROWSER_SCROLL_DEF,
    browser_back,
    BROWSER_BACK_DEF,
    browser_console,
    BROWSER_CONSOLE_DEF,
    browser_vision,
    BROWSER_VISION_DEF,
    browser_get_images,
    BROWSER_GET_IMAGES_DEF,
)
from .keeper import (
    summarize_text,
    embed_text,
    summarize,
    translate,
    SUMMARIZE_TEXT_DEF,
    EMBED_TEXT_DEF,
    SUMMARIZE_DEF,
    TRANSLATE_DEF,
)
from .memory import (
    memory_save,
    memory_delete,
    memory_search,
    MEMORY_SAVE_DEF,
    MEMORY_DELETE_DEF,
    MEMORY_SEARCH_DEF,
)
from .kanban import (
    create_kanban_task,
    list_kanban_tasks,
    update_kanban_task,
    CREATE_KANBAN_TASK_DEF,
    LIST_KANBAN_TASKS_DEF,
    UPDATE_KANBAN_TASK_DEF,
)
from .audio import (
    speech_to_text,
    text_to_speech,
    send_voice_message,
    SPEECH_TO_TEXT_DEF,
    TEXT_TO_SPEECH_DEF,
    SEND_VOICE_MESSAGE_DEF,
)
from .engineering import (
    create_engineering_plan,
    PLAN_DEF,
    test_skill_code,
    TEST_SKILL_DEF,
    register_skill,
    REGISTER_SKILL_DEF,
    update_skill,
    UPDATE_SKILL_DEF,
)
from .debugger import (
    interactive_debugger,
    INTERACTIVE_DEBUGGER_DEF,
)
from .ui_renderer import (
    render_ui_component,
    RENDER_UI_COMPONENT_DEF,
    UI_RENDERING_INSTRUCTIONS,
)
from .db_query import db_query, DB_QUERY_DEF
from .git import (
    git_clone,
    git_status,
    git_commit,
    git_push,
    git_pull,
    git_branch_list,
    git_branch_create,
    git_checkout,
    git_log,
    GIT_CLONE_DEF,
    GIT_STATUS_DEF,
    GIT_COMMIT_DEF,
    GIT_PUSH_DEF,
    GIT_PULL_DEF,
    GIT_BRANCH_LIST_DEF,
    GIT_BRANCH_CREATE_DEF,
    GIT_CHECKOUT_DEF,
    GIT_LOG_DEF,
    GitNotRepoError,
    GitAuthError,
    GitConflictError,
    GitRemoteError,
    GitInvalidOperationError,
)
from .packages import (
    pip_install,
    pip_list,
    PIP_INSTALL_DEF,
    PIP_LIST_DEF,
    PackageInstallError,
    PackageInvalidError,
    PackageTimeoutError,
)
from .secrets import (
    get_secret,
    GET_SECRET_DEF,
    SecretNotFoundError,
    SecretAccessError,
)
from .notifications import (
    notify_user,
    NOTIFY_USER_DEF,
    NotificationRateLimitError,
    NotificationDeliveryError,
)

__all__ = [
    "file_read",
    "file_write",
    "file_list",
    "file_delete",
    "FILE_READ_DEF",
    "FILE_WRITE_DEF",
    "FILE_LIST_DEF",
    "FILE_DELETE_DEF",
    "attach_to_task",
    "ATTACH_TO_TASK_DEF",
    "pull_task_attachment",
    "PULL_TASK_ATTACHMENT_DEF",
    "promote_output",
    "PROMOTE_OUTPUT_DEF",
    "shared_file_read",
    "SHARED_FILE_READ_DEF",
    "shared_file_write",
    "SHARED_FILE_WRITE_DEF",
    "shared_file_list",
    "SHARED_FILE_LIST_DEF",
    "WorkspacePathError",
    "WorkspaceQuotaError",
    "WorkspaceNotFoundError",
    "WorkspacePermissionError",
    "send_message",
    "SEND_MESSAGE_DEF",
    "get_current_datetime",
    "shell_exec",
    "DATETIME_DEF",
    "SHELL_EXEC_DEF",
    "web_fetch",
    "WEB_FETCH_DEF",
    "web_search",
    "WEB_SEARCH_DEF",
    "browser_navigate",
    "BROWSER_NAVIGATE_DEF",
    "browser_snapshot",
    "BROWSER_SNAPSHOT_DEF",
    "browser_click",
    "BROWSER_CLICK_DEF",
    "browser_type",
    "BROWSER_TYPE_DEF",
    "browser_press",
    "BROWSER_PRESS_DEF",
    "browser_scroll",
    "BROWSER_SCROLL_DEF",
    "browser_back",
    "BROWSER_BACK_DEF",
    "browser_console",
    "BROWSER_CONSOLE_DEF",
    "browser_vision",
    "BROWSER_VISION_DEF",
    "browser_get_images",
    "BROWSER_GET_IMAGES_DEF",
    "summarize_text",
    "embed_text",
    "summarize",
    "translate",
    "SUMMARIZE_TEXT_DEF",
    "EMBED_TEXT_DEF",
    "SUMMARIZE_DEF",
    "TRANSLATE_DEF",
    "memory_save",
    "memory_delete",
    "memory_search",
    "MEMORY_SAVE_DEF",
    "MEMORY_DELETE_DEF",
    "MEMORY_SEARCH_DEF",
    "create_kanban_task",
    "CREATE_KANBAN_TASK_DEF",
    "list_kanban_tasks",
    "LIST_KANBAN_TASKS_DEF",
    "update_kanban_task",
    "UPDATE_KANBAN_TASK_DEF",
    "create_engineering_plan",
    "PLAN_DEF",
    "test_skill_code",
    "TEST_SKILL_DEF",
    "register_skill",
    "REGISTER_SKILL_DEF",
    "update_skill",
    "UPDATE_SKILL_DEF",
    "interactive_debugger",
    "INTERACTIVE_DEBUGGER_DEF",
    "speech_to_text",
    "text_to_speech",
    "send_voice_message",
    "SPEECH_TO_TEXT_DEF",
    "TEXT_TO_SPEECH_DEF",
    "SEND_VOICE_MESSAGE_DEF",
    "render_ui_component",
    "RENDER_UI_COMPONENT_DEF",
    "UI_RENDERING_INSTRUCTIONS",
    "db_query",
    "DB_QUERY_DEF",
    "git_clone",
    "git_status",
    "git_commit",
    "git_push",
    "git_pull",
    "git_branch_list",
    "git_branch_create",
    "git_checkout",
    "git_log",
    "GIT_CLONE_DEF",
    "GIT_STATUS_DEF",
    "GIT_COMMIT_DEF",
    "GIT_PUSH_DEF",
    "GIT_PULL_DEF",
    "GIT_BRANCH_LIST_DEF",
    "GIT_BRANCH_CREATE_DEF",
    "GIT_CHECKOUT_DEF",
    "GIT_LOG_DEF",
    "GitNotRepoError",
    "GitAuthError",
    "GitConflictError",
    "GitRemoteError",
    "GitInvalidOperationError",
    "pip_install",
    "pip_list",
    "PIP_INSTALL_DEF",
    "PIP_LIST_DEF",
    "PackageInstallError",
    "PackageInvalidError",
    "PackageTimeoutError",
    "get_secret",
    "GET_SECRET_DEF",
    "SecretNotFoundError",
    "SecretAccessError",
    "notify_user",
    "NOTIFY_USER_DEF",
    "NotificationRateLimitError",
    "NotificationDeliveryError",
    "SKILL_TOOL_REGISTRY",
    "SKILL_CATEGORY_MAP",
    "normalize_skill_name",
]


def normalize_skill_name(skill_name: str) -> str:
    """Normalize a Core skill name to a Python-identifier tool name."""
    return skill_name.replace("-", "_")


# Core hyphenated names (e.g. web-browse-navigate) normalize to keys that may
# differ from SDK registry keys.  This map resolves those mismatches.
SKILL_NAME_ALIASES: dict[str, str] = {
    "web_browse_navigate": "browser_navigate",
    "web_browse_snapshot": "browser_snapshot",
    "web_browse_click": "browser_click",
    "web_browse_type": "browser_type",
    "web_browse_press": "browser_press",
    "web_browse_scroll": "browser_scroll",
    "web_browse_back": "browser_back",
    "web_browse_console": "browser_console",
    "web_browse_vision": "browser_vision",
    "web_browse_images": "browser_get_images",
}


SKILL_TOOL_REGISTRY: dict[str, tuple] = {
    "send_message": (send_message, SEND_MESSAGE_DEF),
    "shell_exec": (shell_exec, SHELL_EXEC_DEF),
    "web_fetch": (web_fetch, WEB_FETCH_DEF),
    "web_search": (web_search, WEB_SEARCH_DEF),
    "summarize_text": (summarize_text, SUMMARIZE_TEXT_DEF),
    "embed_text": (embed_text, EMBED_TEXT_DEF),
    "summarize": (summarize, SUMMARIZE_DEF),
    "translate": (translate, TRANSLATE_DEF),
    "file_read": (file_read, FILE_READ_DEF),
    "file_write": (file_write, FILE_WRITE_DEF),
    "file_list": (file_list, FILE_LIST_DEF),
    "file_delete": (file_delete, FILE_DELETE_DEF),
    "attach_to_task": (attach_to_task, ATTACH_TO_TASK_DEF),
    "pull_task_attachment": (pull_task_attachment, PULL_TASK_ATTACHMENT_DEF),
    "promote_output": (promote_output, PROMOTE_OUTPUT_DEF),
    "shared_file_read": (shared_file_read, SHARED_FILE_READ_DEF),
    "shared_file_write": (shared_file_write, SHARED_FILE_WRITE_DEF),
    "shared_file_list": (shared_file_list, SHARED_FILE_LIST_DEF),
    "memory_save": (memory_save, MEMORY_SAVE_DEF),
    "memory_delete": (memory_delete, MEMORY_DELETE_DEF),
    "memory_search": (memory_search, MEMORY_SEARCH_DEF),
    "create_kanban_task": (create_kanban_task, CREATE_KANBAN_TASK_DEF),
    "list_kanban_tasks": (list_kanban_tasks, LIST_KANBAN_TASKS_DEF),
    "update_kanban_task": (update_kanban_task, UPDATE_KANBAN_TASK_DEF),
    "create_engineering_plan": (create_engineering_plan, PLAN_DEF),
    "test_skill": (test_skill_code, TEST_SKILL_DEF),
    "register_skill": (register_skill, REGISTER_SKILL_DEF),
    "update_skill": (update_skill, UPDATE_SKILL_DEF),
    "interactive_debugger": (interactive_debugger, INTERACTIVE_DEBUGGER_DEF),
    "speech_to_text": (speech_to_text, SPEECH_TO_TEXT_DEF),
    "text_to_speech": (text_to_speech, TEXT_TO_SPEECH_DEF),
    "send_voice_message": (send_voice_message, SEND_VOICE_MESSAGE_DEF),
    "ui_components": (render_ui_component, RENDER_UI_COMPONENT_DEF),
    "db_query": (db_query, DB_QUERY_DEF),
    "git_clone": (git_clone, GIT_CLONE_DEF),
    "git_status": (git_status, GIT_STATUS_DEF),
    "git_commit": (git_commit, GIT_COMMIT_DEF),
    "git_push": (git_push, GIT_PUSH_DEF),
    "git_pull": (git_pull, GIT_PULL_DEF),
    "git_branch_list": (git_branch_list, GIT_BRANCH_LIST_DEF),
    "git_branch_create": (git_branch_create, GIT_BRANCH_CREATE_DEF),
    "git_checkout": (git_checkout, GIT_CHECKOUT_DEF),
    "git_log": (git_log, GIT_LOG_DEF),
    "pip_install": (pip_install, PIP_INSTALL_DEF),
    "pip_list": (pip_list, PIP_LIST_DEF),
    "get_secret": (get_secret, GET_SECRET_DEF),
    "notify_user": (notify_user, NOTIFY_USER_DEF),
    "browser_navigate": (browser_navigate, BROWSER_NAVIGATE_DEF),
    "browser_snapshot": (browser_snapshot, BROWSER_SNAPSHOT_DEF),
    "browser_click": (browser_click, BROWSER_CLICK_DEF),
    "browser_type": (browser_type, BROWSER_TYPE_DEF),
    "browser_press": (browser_press, BROWSER_PRESS_DEF),
    "browser_scroll": (browser_scroll, BROWSER_SCROLL_DEF),
    "browser_back": (browser_back, BROWSER_BACK_DEF),
    "browser_console": (browser_console, BROWSER_CONSOLE_DEF),
    "browser_vision": (browser_vision, BROWSER_VISION_DEF),
    "browser_get_images": (browser_get_images, BROWSER_GET_IMAGES_DEF),
}

SKILL_CATEGORY_MAP: dict[str, str] = {
    "send_message": "communication",
    "shell_exec": "system",
    "web_fetch": "web",
    "web_search": "web",
    "summarize_text": "content",
    "embed_text": "content",
    "summarize": "content",
    "translate": "content",
    "file_read": "workspace",
    "file_write": "workspace",
    "file_list": "workspace",
    "file_delete": "workspace",
    "attach_to_task": "workspace",
    "pull_task_attachment": "workspace",
    "promote_output": "workspace",
    "shared_file_read": "workspace",
    "shared_file_write": "workspace",
    "shared_file_list": "workspace",
    "memory_save": "memory",
    "memory_delete": "memory",
    "memory_search": "memory",
    "create_kanban_task": "kanban",
    "list_kanban_tasks": "kanban",
    "update_kanban_task": "kanban",
    "create_engineering_plan": "engineering",
    "test_skill": "engineering",
    "register_skill": "engineering",
    "update_skill": "engineering",
    "interactive_debugger": "engineering",
    "speech_to_text": "audio",
    "text_to_speech": "audio",
    "send_voice_message": "audio",
    "ui_components": "system",
    "db_query": "database",
    "git_clone": "git",
    "git_status": "git",
    "git_commit": "git",
    "git_push": "git",
    "git_pull": "git",
    "git_branch_list": "git",
    "git_branch_create": "git",
    "git_checkout": "git",
    "git_log": "git",
    "pip_install": "workspace",
    "pip_list": "workspace",
    "get_secret": "system",
    "get_current_datetime": "system",
    "notify_user": "communication",
    "browser_navigate": "web",
    "browser_snapshot": "web",
    "browser_click": "web",
    "browser_type": "web",
    "browser_press": "web",
    "browser_scroll": "web",
    "browser_back": "web",
    "browser_console": "web",
    "browser_vision": "web",
    "browser_get_images": "web",
}
