server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 valid=30s;
    client_max_body_size 10M;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $core_backend "http://core:8000";
        rewrite ^/api/(.*) /$1 break;
        proxy_pass $core_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    }

    location /channels-api/ {
        set $channels_backend "http://channels:8200";
        rewrite ^/channels-api/(.*) /$1 break;
        proxy_pass $channels_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    }
}
