"""add last_message_at to sessions

Revision ID: 11d2a499d4c2
Revises: 643385a74bb8
Create Date: 2026-05-20 21:02:00.083188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d2a499d4c2'
down_revision: Union[str, None] = '643385a74bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_sessions_last_message_at', 'sessions', ['last_message_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_last_message_at', table_name='sessions')
    op.drop_column('sessions', 'last_message_at')
    # ### end Alembic commands ###
