"""add session status and context_summary

Revision ID: 5d394360388c
Revises: 0bad60745eba
Create Date: 2026-05-17 23:52:25.711946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d394360388c'
down_revision: Union[str, None] = '0bad60745eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('sessions', sa.Column('context_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'context_summary')
    op.drop_column('sessions', 'status')
    # ### end Alembic commands ###
