"""add_agent_picture

Revision ID: 785c62fa414a
Revises: 8dd5e6f4bee6
Create Date: 2026-06-07 18:02:01.826027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785c62fa414a'
down_revision: Union[str, None] = '8dd5e6f4bee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('picture', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'picture')
    # ### end Alembic commands ###
