"""add_persona_to_agent

Revision ID: 643385a74bb8
Revises: 5048e15435b6
Create Date: 2026-05-19 23:02:18.690506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643385a74bb8'
down_revision: Union[str, None] = '5048e15435b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('persona', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'persona')
    # ### end Alembic commands ###
