/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst } from 'workbox-strategies'

declare const self: ServiceWorkerGlobalScope

cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Cache API requests
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
  })
)

// Push Notification Listener
self.addEventListener('push', (event) => {
  if (!event.data) return

  try {
    const data = event.data.json()
    const options = {
      body: data.body,
      icon: '/favicon.png',
      badge: '/favicon.png',
      data: data.data, // Custom data like notification_id
      vibrate: [100, 50, 100],
      actions: [
        { action: 'open', title: 'Open Board' }
      ]
    }

    event.waitUntil(
      self.registration.showNotification(data.title || 'ISLI Notification', options)
    )
  } catch (err) {
    console.error('Push event error:', err)
  }
})

// Notification Click Listener
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  // Deep link logic: task -> kanban, session -> chats, agent -> dashboard
  const notificationData = event.notification.data
  let url = '/'

  if (notificationData && notificationData.task_id) {
    url = `/kanban?task=${notificationData.task_id}`
  } else if (notificationData && notificationData.session_id) {
    url = `/chats?session=${notificationData.session_id}`
  } else if (notificationData && notificationData.agent_id) {
    url = `/?agent=${notificationData.agent_id}`
  }

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url === url && 'focus' in client) {
          return (client as any).focus()
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(url)
      }
    })
  )
})
