# ISLI Native Windows Installer (PowerShell)
# Checks Python/Node, creates venvs, installs deps, creates start scripts.
# Run as Administrator if you want to create Windows services (optional).

param(
    [string]$InstallDir = "C:\ISLI",
    [switch]$CreateServices
)

$ErrorActionPreference = "Stop"

function Test-Command {
    param([string]$Name)
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

Write-Host "[install-native] ISLI native Windows installer" -ForegroundColor Cyan

# --- Checks ---
if (-not (Test-Command python)) {
    Write-Error "Python is not installed. Please install Python 3.12 from https://python.org"
    exit 1
}
if (-not (Test-Command node)) {
    Write-Error "Node.js is not installed. Please install Node.js 22 from https://nodejs.org"
    exit 1
}
if (-not (Test-Command npm)) {
    Write-Error "npm is not found. Please install Node.js 22."
    exit 1
}

$pyVersion = python --version 2>&1
Write-Host "[install-native] Found $pyVersion"
$nodeVersion = node --version 2>&1
Write-Host "[install-native] Found Node $nodeVersion"

# --- Create install dir ---
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir | Out-Null
}
$ProjectRoot = Split-Path -Parent $PSScriptRoot
Write-Host "[install-native] Copying project to $InstallDir"
Copy-Item -Path "$ProjectRoot\*" -Destination $InstallDir -Recurse -Force

# --- .env ---
$EnvFile = Join-Path $InstallDir ".env"
if (-not (Test-Path $EnvFile)) {
    Copy-Item -Path (Join-Path $InstallDir ".env.production") -Destination $EnvFile -Force
    Write-Host "[install-native] Created .env from template. EDIT IT BEFORE STARTING SERVICES." -ForegroundColor Yellow
}

# --- Python services ---
$services = @("isli-core", "isli-keeper", "isli-channels", "isli-skills")
foreach ($svc in $services) {
    Write-Host "[install-native] Setting up $svc..."
    $svcDir = Join-Path $InstallDir $svc
    $venvDir = Join-Path $svcDir ".venv"
    python -m venv $venvDir
    & "$venvDir\Scripts\pip.exe" install --upgrade pip
    & "$venvDir\Scripts\pip.exe" install -e "$svcDir[dev]"
}

# --- Board ---
Write-Host "[install-native] Setting up isli-board..."
$boardDir = Join-Path $InstallDir "isli-board"
Set-Location $boardDir
& npm ci
& npm run build
Set-Location $PSScriptRoot

# --- Start scripts ---
$startScript = Join-Path $InstallDir "start-isli.ps1"
$stopScript = Join-Path $InstallDir "stop-isli.ps1"

$startContent = @"
# ISLI Start Script (generated by install-native.ps1)
`$ProjectRoot = "$InstallDir"
`$Pids = @()

function Start-ServiceProc {
    param(`$Name, `$Dir, `$Cmd, `$Args)
    Write-Host "Starting `$Name..."
    `$proc = Start-Process -FilePath `$Cmd -ArgumentList `$Args -WorkingDirectory `$Dir -PassThru -WindowStyle Hidden
    return `$proc.Id
}

`$Pids += Start-ServiceProc -Name "isli-core" -Dir "`$ProjectRoot\isli-core" -Cmd "`$ProjectRoot\isli-core\.venv\Scripts\python.exe" -Args "-m uvicorn isli_core.main:app --host 0.0.0.0 --port 8000"
`$Pids += Start-ServiceProc -Name "isli-keeper" -Dir "`$ProjectRoot\isli-keeper" -Cmd "`$ProjectRoot\isli-keeper\.venv\Scripts\python.exe" -Args "-m uvicorn isli_keeper.main:app --host 0.0.0.0 --port 8001"
`$Pids += Start-ServiceProc -Name "isli-channels" -Dir "`$ProjectRoot\isli-channels" -Cmd "`$ProjectRoot\isli-channels\.venv\Scripts\python.exe" -Args "-m uvicorn isli_channels.main:app --host 0.0.0.0 --port 8002"
`$Pids += Start-ServiceProc -Name "isli-skills" -Dir "`$ProjectRoot\isli-skills" -Cmd "`$ProjectRoot\isli-skills\.venv\Scripts\python.exe" -Args "-m uvicorn isli_skills.main:app --host 0.0.0.0 --port 8003"
`$Pids += Start-ServiceProc -Name "isli-board" -Dir "`$ProjectRoot\isli-board" -Cmd "node" -Args "serve dist"

`$Pids | Out-File -FilePath (Join-Path `$ProjectRoot ".isli-pids")
Write-Host "ISLI started. PIDs saved to .isli-pids"
"@

$stopContent = @"
# ISLI Stop Script (generated by install-native.ps1)
`$pidFile = "$InstallDir\.isli-pids"
if (Test-Path `$pidFile) {
    `$ids = Get-Content `$pidFile
    foreach (`$id in `$ids) {
        if (`$id -match '^\d+`$') {
            Write-Host "Stopping PID `$id..."
            Stop-Process -Id `$id -Force -ErrorAction SilentlyContinue
        }
    }
    Remove-Item `$pidFile -Force
    Write-Host "ISLI stopped."
} else {
    Write-Host "No PID file found."
}
"@

$startContent | Out-File -FilePath $startScript -Encoding utf8
$stopContent | Out-File -FilePath $stopScript -Encoding utf8

Write-Host "[install-native] Created start script: $startScript"
Write-Host "[install-native] Created stop script: $stopScript"

# --- Optional Windows services via NSSM ---
if ($CreateServices) {
    if (-not (Test-Command nssm)) {
        Write-Warning "NSSM not found. Install NSSM to create Windows services: https://nssm.cc"
    } else {
        Write-Host "[install-native] Creating Windows services with NSSM..."
        foreach ($svc in $services) {
            $svcName = $svc
            $display = "ISLI $svc"
            $exe = Join-Path $InstallDir "$svc\.venv\Scripts\python.exe"
            $args = "-m uvicorn $($svc -replace '-','_').main:app --host 0.0.0.0 --port $(switch($svc){'isli-core'{8000}'isli-keeper'{8001}'isli-channels'{8002}'isli-skills'{8003}})"
            nssm install $svcName $exe $args
            nssm set $svcName DisplayName $display
            nssm set $svcName AppDirectory (Join-Path $InstallDir $svc)
            nssm start $svcName
        }
    }
}

Write-Host "[install-native] Done. Start with: & '$startScript'" -ForegroundColor Green
Write-Host "[install-native] Stop with: & '$stopScript'" -ForegroundColor Green
Write-Host "[install-native] IMPORTANT: Edit $EnvFile before starting services." -ForegroundColor Yellow
