import { useAgents } from '@/hooks/useAgents'
import { StatusBadge } from './StatusBadge'
import { FolderGit2, HardDrive, ArrowRight, Bot, Cpu } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Link } from 'react-router-dom'

export function WorkspacesPage() {
  const { data: agents = [], isLoading } = useAgents()

  if (isLoading) {
    return (
      <div className="flex-1 flex items-center justify-center bg-bg-base">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-accent-cyan/20 border-t-accent-cyan rounded-full animate-spin" />
          <span className="text-sm font-display font-medium text-text-muted animate-pulse">
            Loading workspaces...
          </span>
        </div>
      </div>
    )
  }

  return (
    <div className="flex-1 overflow-y-auto bg-bg-base p-6 md:p-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <h1 className="text-2xl font-display font-bold text-text-primary flex items-center gap-3">
            <FolderGit2 className="w-8 h-8 text-accent-cyan" />
            Workspaces
          </h1>
          <p className="text-text-secondary mt-1 max-w-xl">
            Browse and manage files generated by each agent in their respective sandboxed environments.
          </p>
        </div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {agents.map((agent) => (
          <Link
            key={agent.id}
            to={`/workspaces/${agent.id}`}
            className={cn(
              'group flex flex-col p-5 rounded-2xl bg-bg-surface border border-border-dim',
              'hover:border-accent-cyan hover:shadow-card-hover hover:-translate-y-1',
              'transition-all duration-300 relative overflow-hidden'
            )}
          >
            {/* Background decoration */}
            <div className="absolute top-0 right-0 p-8 -mr-8 -mt-8 opacity-[0.03] group-hover:opacity-[0.07] transition-opacity">
              <HardDrive className="w-32 h-32" />
            </div>

            <div className="flex items-start justify-between mb-4 relative z-10">
              <div className="w-12 h-12 rounded-xl bg-bg-elevated border border-border-dim flex items-center justify-center text-accent-cyan group-hover:border-accent-cyan/50 transition-colors">
                <Cpu className="w-6 h-6" />
              </div>
              <StatusBadge status={agent.status} />
            </div>

            <div className="mb-4 relative z-10">
              <h3 className="text-lg font-display font-bold text-text-primary group-hover:text-accent-cyan transition-colors truncate">
                {agent.name}
              </h3>
              <p className="text-xs font-mono-data text-text-muted mt-1 uppercase tracking-tighter">
                {agent.id}
              </p>
            </div>

            <div className="mt-4 flex items-center justify-between relative z-10 pt-4 border-t border-border-dim">
              <span className="text-xs text-text-secondary">View Files</span>
              <div className="text-accent-cyan opacity-0 group-hover:opacity-100 transform translate-x-2 group-hover:translate-x-0 transition-all">
                <ArrowRight className="w-5 h-5" />
              </div>
            </div>
          </Link>
        ))}

        {agents.length === 0 && (
          <div className="col-span-full flex flex-col items-center justify-center py-20 border-2 border-dashed border-border-dim rounded-3xl bg-bg-surface/30">
            <Bot className="w-16 h-16 text-text-muted mb-4 opacity-20" />
            <h3 className="text-xl font-display font-bold text-text-secondary">No Agents Available</h3>
            <p className="text-text-muted text-center max-w-xs">
              Workspaces are automatically created for each agent.
            </p>
          </div>
        )}
      </div>
    </div>
  )
}
